package models

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Notification represents an in-app notification for any user type.
type Notification struct {
	ID        uuid.UUID       `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`
	UserID    uuid.UUID       `gorm:"type:uuid;not null;index" json:"user_id"`
	Type      string          `gorm:"not null;size:50" json:"type"` // order_update, review, promotion, system
	Title     string          `gorm:"not null;size:255" json:"title"`
	Message   *string         `json:"message"`
	IsRead    bool            `gorm:"default:false" json:"is_read"`
	ActionURL *string         `json:"action_url"`
	Data      json.RawMessage `gorm:"type:jsonb;default:'{}'" json:"data"`
	CreatedAt time.Time       `json:"created_at"`

	// Relations
	User User `gorm:"foreignKey:UserID" json:"-"`
}

// TableName overrides the default table name.
func (Notification) TableName() string {
	return "notifications"
}

// BrowsingHistory tracks product views for the AI recommendation engine.
type BrowsingHistory struct {
	ID        uuid.UUID `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`
	UserID    uuid.UUID `gorm:"type:uuid;not null;index" json:"user_id"`
	ProductID uuid.UUID `gorm:"type:uuid;not null" json:"product_id"`
	ViewedAt  time.Time `gorm:"default:now()" json:"viewed_at"`

	// Relations
	User    User    `gorm:"foreignKey:UserID" json:"-"`
	Product Product `gorm:"foreignKey:ProductID" json:"product,omitempty"`
}

// TableName overrides the default table name.
func (BrowsingHistory) TableName() string {
	return "browsing_history"
}

// AIRecommendation stores personalized product suggestions generated by the
// AI recommendation engine.
type AIRecommendation struct {
	ID        uuid.UUID  `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`
	UserID    uuid.UUID  `gorm:"type:uuid;not null;index" json:"user_id"`
	ProductID uuid.UUID  `gorm:"type:uuid;not null" json:"product_id"`
	Score     float64    `gorm:"type:decimal(5,4);not null" json:"score"`
	Reason    *string    `json:"reason"`
	Algorithm string     `gorm:"size:50;default:collaborative" json:"algorithm"`
	ExpiresAt *time.Time `json:"expires_at"`
	CreatedAt time.Time  `json:"created_at"`

	// Relations
	User    User    `gorm:"foreignKey:UserID" json:"-"`
	Product Product `gorm:"foreignKey:ProductID" json:"product,omitempty"`
}

// TableName overrides the default table name.
func (AIRecommendation) TableName() string {
	return "ai_recommendations"
}

// NotificationListQuery holds query parameters for listing notifications.
type NotificationListQuery struct {
	Page    int    `json:"page"`
	PerPage int    `json:"per_page"`
	Type    string `json:"type"`
	Unread  *bool  `json:"unread"`
}

// MarkNotificationReadRequest is used to mark one or more notifications as read.
type MarkNotificationReadRequest struct {
	NotificationIDs []string `json:"notification_ids" validate:"required,min=1"`
}

// BrowsingHistoryEntry is the payload for recording a product view.
type BrowsingHistoryEntry struct {
	ProductID string `json:"product_id" validate:"required,uuid"`
}
